name: Build Mobile Apps

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ios:
    name: iOS Build (unsigned)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (robust)
        run: |
          rm -rf node_modules
          npm ci || (echo "npm ci failed; falling back to npm install" && rm -f package-lock.json && npm install)

      - name: Build web assets
        run: npm run build

      - name: Prepare iOS icons/splashes
        run: npx capacitor-assets generate --ios --iconBackgroundColor "#000000" --splashBackgroundColor "#000000"

      - name: Add iOS platform if missing
        run: |
          test -d ios || npx cap add ios

      - name: Capacitor sync iOS
        run: npx cap sync ios

      - name: Patch iOS Info.plist (Files visibility)
        run: node scripts/patch-ios-filesharing.cjs

      - name: Patch LaunchScreen.storyboard (brand label)
        run: node scripts/patch-ios-launchscreen.cjs

      - name: Install CocoaPods
        run: |
          cd ios/App
          pod install --repo-update

      - name: Build iOS app (unsigned)
        run: |
          set -e
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO build
          echo "Listing products:"
          ls -R ~/Library/Developer/Xcode/DerivedData || true

      - name: Collect .app bundle
        run: |
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -path "*Build/Products/Release-iphoneos/*.app" | head -n1 || true)
          if [ -z "$APP_PATH" ]; then echo "No .app found"; exit 1; fi
          mkdir -p build-ios
          cp -R "$APP_PATH" build-ios/
          echo "Copied $APP_PATH to build-ios/"

      - name: Package unsigned IPA
        run: |
          set -e
          APP_PATH=$(ls -d build-ios/*.app | head -n1)
          [ -d "$APP_PATH" ] || (echo "No .app for packaging" && exit 1)
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -qry build-ios/app-unsigned.ipa Payload
          rm -rf Payload
          echo "IPA created at build-ios/app-unsigned.ipa"

      - name: Upload iOS artifact (.app, unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-unsigned
          path: build-ios/*.app

      - name: Upload iOS IPA (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-unsigned
          path: build-ios/*.ipa

      # NOTE: For a signed IPA, add Apple certs/profiles as GitHub Secrets and run archive/export.
