name: Deploy OTA (Firebase Hosting)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (with fallback for npm optional deps bug)
        run: |
          rm -rf node_modules
          npm ci || (echo "npm ci failed; falling back to npm install without lock" && rm -f package-lock.json && npm install)

      - name: Build app
        run: npm run build

      - name: Prepare OTA artifact and manifest
        env:
          HOST: https://time-tracker-e36f1.web.app
        run: |
          VERSION="${GITHUB_REF_NAME:-v0.0.0}"
          mkdir -p hosting/updates/stable
          cd dist
          zip -r ../hosting/updates/stable/app-${VERSION}.zip .
          cd ..
          SHA256=$(shasum -a 256 hosting/updates/stable/app-${VERSION}.zip | awk '{print $1}')
          cat > hosting/updates/stable/manifest.json <<EOF
          {
            "version": "${VERSION}",
            "url": "${HOST}/updates/stable/app-${VERSION}.zip",
            "sha256": "${SHA256}",
            "createdAt": "$(date -u +%FT%TZ)"
          }
          EOF

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project time-tracker-e36f1 --non-interactive
